//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestitonalePazienti.Martina.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paziente
    {
        public Paziente() { }
        public Paziente(string nome, string cognome, DateTime dataDiNascita, string luogoDiNascita,
                        string codiceFiscale)
        {
            Nome = nome;
            Cognome = cognome;
            DataDiNascita = dataDiNascita;
            LuogoDiNascita = luogoDiNascita;
            CodiceFiscale = codiceFiscale;
            CognomeNome = cognome + " " + nome;
        }
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string CognomeNome { get; set; }
        public System.DateTime DataDiNascita { get; set; }
        public string LuogoDiNascita { get; set; }
        public string CodiceFiscale { get; set; }
    }
}
